BEGIN;

CREATE TYPE pet_type AS ENUM ('cat', 'dog');

CREATE TABLE IF NOT EXISTS pets (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  pet_type pet_type,
  image_url TEXT,
  image_description TEXT,
  name TEXT,
  gender TEXT,
  age INTEGER,
  breed TEXT,
  story TEXT,
  date_entered TIMESTAMP DEFAULT now() NOT NULL
);

COMMIT;